### ISSUE TITLE
Degraded performance under heavy load

### ISSUE THREAD

**Issue by sanketplus** [mk23/jmxproxy#141] opened 2017-01-13 10:59 UTC
I am using JMXProxy for around 70 JVM to query full data (full=true) and it is load balanced between 2 JMXProxy instances. 

I am hitting JMXProxy continuously with around 1 minute of sleep time. But after a point it gets really slow. It takes seconds (10s of seconds) to reply. 

How many queries/load it is expected to handle?

**Comment by mk23** [comment] 2017-01-21 02:55
This is different than #142 in that this is caused by serializing access to the global host map.  #142 is related, but really caused by lack of a proper connection timeout which sends the server into a blackhole while it's failing to connect.  Both issues will be fixed separately.

**Closed** 2017-01-22 07:12 UTC
Labels: backend api, bug
